# Generated by Django 3.2.5 on 2022-03-24 21:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manageImages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('b2d587fe-7418-43f9-b880-1d5f536652a5'), primary_key=True, serialize=False),
        ),
    ]
