# Generated by Django 2.2.26 on 2022-03-30 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manageImages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('131720c1-0cf8-490c-acdb-c41686f594aa'), primary_key=True, serialize=False),
        ),
    ]
