# Generated by Django 3.2.5 on 2022-03-15 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manageImages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('8f3eea05-9892-4543-8bd7-558665d9eec7'), primary_key=True, serialize=False),
        ),
    ]
