# Generated by Django 3.2.5 on 2022-03-16 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manageImages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('b89bb04a-a976-4220-9518-40c69dc02e25'), primary_key=True, serialize=False),
        ),
    ]
