# Generated by Django 3.2.5 on 2022-03-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageImages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Picture',
        ),
    ]
