# Generated by Django 3.2.5 on 2022-03-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageImages', '0002_rename_page_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='userImages'),
        ),
    ]
