# Generated by Django 3.2.5 on 2022-03-24 21:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manageImages', '0002_alter_picture_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('4ed4e6d1-f1ca-41e0-a17a-bf641e32e0db'), primary_key=True, serialize=False),
        ),
    ]
