# Generated by Django 3.2.5 on 2022-03-16 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageImages', '0002_alter_picture_id'),
        ('manageImages', '0002_auto_20220306_2111'),
    ]

    operations = [
    ]
