# Generated by Django 3.2.5 on 2022-03-18 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manageImages', '0002_alter_picture_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('8a1fb177-7db8-448b-baa6-f6769ec1287d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='picture_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='manageImages.picture'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
