# Generated by Django 3.2.5 on 2022-03-18 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manageImages', '0003_auto_20220318_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('5f6f53bc-35a6-435f-a5bb-db23d63c1f9a'), primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='like',
            name='picture_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='manageImages.picture'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dislike',
            name='picture_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='manageImages.picture'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
