# Generated by Django 3.2.5 on 2022-03-16 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manageImages', '0003_merge_0002_alter_picture_id_0002_auto_20220306_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote_id',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_type',
        ),
        migrations.AddField(
            model_name='vote',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='like',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='picture_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manageImages.picture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='user_ID',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('910fa372-54a1-4ed0-bb2d-a073d5d86fdb'), primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Total',
        ),
    ]
